obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[2.5, 2], [2.5, -2], [-2.5, -2], [-2.5, 2]]
footprint_inflation: 0.1
max_obstacle_height: 1.2
min_obstacle_height: 0.2
observation_sources: front_stereo_pointcloud2 rear_stereo_pointcloud2
front_stereo_pointcloud2: {data_type: PointCloud, topic: /front_stereo/pointcloud2, marking: true, clearing: true, expected_update_rate: 0}
rear_stereo_pointcloud2: {data_type: PointCloud, topic: /rear_stereo/pointcloud2, marking: true, clearing: true, expected_update_rate: 0}
