controller_frequency: 3.0
recovery_behavior_enabled: true
clearing_rotation_allowed: false

NavfnROS:
  allow_unknown: true # Specifies whether or not to allow navfn to create plans that traverse unknown space.
  default_tolerance: 0.1 # A tolerance on the goal point for the planner.

TrajectoryPlannerROS:
   max_vel_x: 2.0
   min_vel_x: 0.1
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   min_in_place_vel_theta: 0.5
   escape_vel: -0.5
   acc_lim_x: 1.5
   acc_lim_y: 0.0 # zero for a differential drive robot
   acc_lim_theta: 1.5

   holonomic_robot: false
   yaw_goal_tolerance: 0.5 # about 30 degrees
   xy_goal_tolerance: 1  # 1 m
   latch_xy_goal_tolerance: false
   pdist_scale: 0.9
   gdist_scale: 0.1
   meter_scoring: true

   heading_lookahead: 0.5
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.1
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 8
   vy_samples: 0 # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false

DWAPlannerROS:
  # Robot configuration parameters  
  acc_lim_x: 1.1
  acc_lim_y: 0
  acc_lim_th: 1.5

  max_vel_x: 2.5
  min_vel_x: 0.5
  max_vel_y: 0
  min_vel_y: 0

  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.0
  min_rot_vel: 0.2

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 1.0
  latch_xy_goal_tolerance: false

