obstacle_range: 4.5
raytrace_range: 5

footprint: [[2.5, 2], [2.5, -2], [-2.5, -2], [-2.5, 2]]
footprint_padding: 0.05

max_obstacle_height: 1.2
min_obstacle_height: 0.2

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 10

resolution: 1

static:
    map_topic: /map
    subscribe_to_updates: true

obstacle_laser:
    observation_sources: bow_stereo_pointcloud port_stereo_pointcloud starboard_stereo_pointcloud
    bow_stereo_pointcloud: 
        {data_type: PointCloud, topic: /bow_stereo/points2, marking: true, clearing: true, expected_update_rate: 0, inf_is_valid: true}
    port_stereo_pointcloud: 
        {data_type: PointCloud, topic: /port_stereo/points2, marking: true, clearing: true, expected_update_rate: 0, inf_is_valid: true}
    starboard_stereo_pointcloud: 
        {data_type: PointCloud, topic: /starboard_stereo/points2, marking: true, clearing: true, expected_update_rate: 0, inf_is_valid: true}

inflation:
    inflation_radius: 0.5
