obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.4, 0.2], [0.4, -0.2], [-0.4, -0.2], [-0.4, 0.2]]
footprint_inflation: 0.3
max_obstacle_height: 0.6
min_obstacle_height: 0.0
# observation_sources: scan
# scan: {data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true, expected_update_rate: 0}
