obstacle_range: 2.5
raytrace_range: 3
footprint: [[2.5, 2.0], [2.5, -2.0], [-2.5, -2.0], [-2.5, 2.0]]
footprint_inflation: 0.5
#robot_radius: 0.175
inflation_radius: 0.5
max_obstacle_height: 0
min_obstacle_height: 0
# observation_sources: scan
# scan: {data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true, expected_update_rate: 0}
