<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="auv" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Constants for robot dimensions -->
    <xacro:property name="PI" value="3.1415926535897931"/>
    <xacro:property name="wheel_mass" value="0.5" /> 
    <xacro:property name="wheel_separation" value="0.5" /> 
    <xacro:property name="wheel_radius" value="0.12" /> 
    <xacro:property name="wheel_thickness" value="0.05" /> 

    <!--xacro:include filename="materials.xacro" /-->

    <!-- macro for wheel -->
    <xacro:macro name="wheel" params="position1 position2">

        <link name="${position1}_${position2}_wheel_link">
            <collision>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                </geometry>
            </collision>

            <!--visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
                <geometry>
                    <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
                </geometry>
                <material name="black"/>
            </visual-->

            <inertial>
                <mass value="${wheel_mass}"/>
                <inertia
                    ixx="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                    iyy="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                    izz="${wheel_mass / 2.0 * wheel_radius*wheel_radius}"/>
            </inertial>
        </link>
    </xacro:macro>


    <!-- left wheel -->
    <joint name="front_left_wheel_joint" type="continuous">
        <axis xyz="0 1 0" />
        <parent link="base_link"/>
        <child link="front_left_wheel_link"/>
        <origin xyz="${wheel_separation/2} ${-1*wheel_separation/2} 0" rpy="0 0 0"/>
    </joint>

    <xacro:wheel position1="front" position2="left"/>

    <joint name="back_left_wheel_joint" type="continuous">
        <axis xyz="0 1 0" />
        <parent link="base_link"/>
        <child link="back_left_wheel_link"/>
        <origin xyz="${-1*wheel_separation/2} ${-1*wheel_separation/2} 0" rpy="0 0 0"/>
    </joint>

    <xacro:wheel position1="back" position2="left"/>
    <!-- right wheel -->
    <joint name="front_right_wheel_joint" type="continuous">
        <axis xyz="0 1 0" />
        <parent link="base_link"/>
        <child link="front_right_wheel_link"/>
        <origin xyz="${wheel_separation/2} ${wheel_separation/2} 0" rpy="0 0 0"/>
    </joint>

    <xacro:wheel position1="front" position2="right"/>

    <joint name="back_right_wheel_joint" type="continuous">
        <axis xyz="0 1 0" />
        <parent link="base_link"/>
        <child link="back_right_wheel_link"/>
        <origin xyz="${-1*wheel_separation/2} ${wheel_separation/2} 0" rpy="0 0 0"/>
    </joint>

    <xacro:wheel position1="back" position2="right"/>

</robot>
